spring.application.name=backend
spring.profiles.active=prod

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${DB_PORT:5432}/${POSTGRES_DB:nexus}}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.web.error.include-stacktrace=never

nexus.jwt.secret=${JWT_SECRET}
