spring.application.name=backend
spring.profiles.active=dev

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${DB_PORT:5432}/${POSTGRES_DB:nexus}}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.web.error.include-stacktrace=never

nexus.jwt.secret=${JWT_SECRET:chave-secreta-nexus-default}
